# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - go build -o tmp/api ./cmd/api/...
    silent: true
  run:
    cmds:
      - air
    silent: true
  default:
    cmds:
      - task: run
  test:
    cmds:
      - go test -v ./cmd/api/...
